### ISSUE TITLE
Pressing Enter on any entry property, crashes the program.

### ISSUE THREAD

**Issue by xFN10x** [samyeyo/RTBuilder#8]

**Comment by samyeyo** [comment]
Thank you for this report, I was able to reproduce this issue too

**Comment by xFN10x** [comment]
i think it may be a problem with tracker.c/h

**Comment by xFN10x** [comment]
but i only kinda know c#, so I'm not sure

**Comment by samyeyo** [comment]
It's fixed, I'm pushing the commit in a few sec 👍

**Comment by samyeyo** [comment]
Have you tested the last commit ? For me it seems ok
